

        EXTERN _UpdatePlayer
        EXTERN _RenderPlayer
        EXTERN _LoadRaw
        EXTERN _FirePlayerWeapons
        EXTERN _FirePlayerMainThrusters
        EXTERN _FirePlayerLeftThrusters
        EXTERN _FirePlayerRightThrusters
        EXTERN _DrawPlayerHealth
        EXTERN _DetectPlayerCollisions
        EXTERN _InitPlayer
        EXTERN _DestroyPlayer

        EXTERN _intPlayerX
        EXTERN _intPlayerY
        EXTERN _intbPlayerAngle
        EXTERN _intbPlayerTurnDir
        EXTERN _fltPlayerX
        EXTERN _fltPlayerY
        EXTERN _fltPlayerSpeed
        EXTERN _PlayerShipOff
        EXTERN _PlayerShipOffL
        EXTERN _PlayerShipOffR
        EXTERN _fltPlayerAccel
        EXTERN _fltPlayerFriction
        EXTERN _fltPlayerMaxSpeed
        EXTERN _fltPlayerMinSpeed
        EXTERN _fltPlayerStrafeSpeed
        EXTERN _fltPlayerStrafeFriction
        EXTERN _fltPlayerMaxStrafeSpeed
        EXTERN _fltPlayerMinStrafeSpeed
        EXTERN _fltPlayerMass
        EXTERN _fltPlayerNoseX
        EXTERN _fltPlayerNoseY
        EXTERN _fltPlayerTailX
        EXTERN _fltPlayerTailY
        EXTERN _intPlayerNoseX
        EXTERN _intPlayerNoseY
        EXTERN _intPlayerTailX
        EXTERN _intPlayerTailY
        EXTERN _intPlayerHealth
        EXTERN _intPlayerWeaponsLevel




